### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by totalitarian** [LightwaveSmartHome/homeassistant-lightwave-smart#10]
Hi, I get this error every day. Only way to fix it seems to be to delete the component and re-add each time. Any ideas?

```
Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 19:53:42 (1 occurrences)
Last logged: 19:53:42

Error setting up entry xxxx@gmail.com for lightwave_smart
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lightwave_smart/__init__.py", line 89, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.12/site-packages/lightwave_smart/lightwave_smart.py", line 625, in async_get_hierarchy
    await self.async_update_featureset_states()
  File "/usr/local/lib/python3.12/site-packages/lightwave_smart/lightwave_smart.py", line 676, in async_update_featureset_states
    await self._ws._async_sendmessage(message, process_read_item_cb)
  File "/usr/local/lib/python3.12/site-packages/lightwave_smart/lightwave_smart.py", line 361, in _async_sendmessage
    elif _retry >= MAX_RETRIES:
         ^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'function' and 'int'


```

**Comment by safzal** [comment]
Hi I am getting error as well but mine is little different:

`Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 00:11:56 (1 occurrences)
Last logged: 00:11:56

Error setting up entry xxxxx@xxxx.com for lightwave_smart
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lightwave_smart/__init__.py", line 86, in async_setup_entry
    connected = await link.async_connect(max_tries = 1, force_keep_alive_secs=0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lightwave_smart/lightwave_smart.py", line 797, in async_connect
    return await self._ws.async_connect(max_tries, force_keep_alive_secs)
                 ^^^^^^^^
AttributeError: 'LWLink2Public' object has no attribute '_ws'
`

**Comment by safzal** [comment]
I have just fixed my error by just added 
```
 File "/config/custom_components/lightwave_smart/__init__.py", line 86, in async_setup_entry
    connected = await link.async_connect(max_tries = 1, force_keep_alive_secs=0)

->> 

 File "/config/custom_components/lightwave_smart/__init__.py", line 86, in async_setup_entry
    connected = await link.async_connect(max_tries = 1, force_keep_alive_secs=30)
```

so by every 30 sec with will check then 0 sec

**Comment by ikb42** [comment]
Hi, will try to repeat this issue locally and revert back here.

**Comment by ikb42** [comment]
@safzal  @totalitarian 
please try the latest beta - [3.5.33](https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/releases/tag/v3.5.33-Beta)

**Comment by ikb42** [comment]
Please see the latest beta [v3.5.37](https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/releases/tag/v3.5.37-Beta)
Can anyone confirm if this is solved now?
