### ISSUE TITLE
Lightwave Smart custom component: Set Brightness - give unknown error

### ISSUE THREAD

**Issue by ins4neuk** [LightwaveSmartHome/homeassistant-lightwave-smart#12]
when i try to use the Set Brightness it just returns unknown error, cant get this to work in a service call or an automation etc

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/lightwave_smart/light.py:84
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 00:26:52 (9 occurrences)
Last logged: 01:03:07

[139954799390528] Error handling message: Unknown error (unknown_error) admin from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36)
[139955557216960] Error handling message: Unknown error (unknown_error) admin from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36)
[139955190868416] Error handling message: Unknown error (unknown_error) admin from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 793, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/lightwave_smart/light.py", line 84, in service_handle_brightness
    _LOGGER.debug("Received service call set brightness %s", light._name)
                                                             ^^^^^^^^^^^
AttributeError: 'LWRF2Light' object has no attribute '_name'. Did you mean: 'name'?

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:501
First occurred: 00:26:52 (9 occurrences)
Last logged: 01:03:07

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'LWRF2Light' object has no attribute '_name'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/lightwave_smart/light.py", line 84, in service_handle_brightness
    _LOGGER.debug("Received service call set brightness %s", light._name)
                                                             ^^^^^^^^^^^
AttributeError: 'LWRF2Light' object has no attribute '_name'. Did you mean: 'name'?

Ideally provide output from homeassistant.log, preferably with additional logging enabled.

To enable additional logging, add the following to configuration.yaml

logger:
  default: warning
  logs:
    lightwave_smart.lightwave_smart: debug
    custom_components.lightwave_smart: debug

**Comment by roboberk** [comment]
I am also getting this same error when trying to use lightwave_smart.set_brightness

**Comment by ins4neuk** [comment]
And body any ideas as I'm going to have to remove some of my automations where lights are dynamically set via motion etc.

**Comment by RGarrett93** [comment]
Have you looked into using HomeKit (within HA), I use that for my primary light switching and brightness control when turning on: which is all done under local control (not via cloud to Lightwave server).
I use this integration for multi-touch detection and others functionality, but unfortunately I'm having a few issues myself that I've raised on here.

**Comment by RMMTSLLP** [comment]
Hi Guys,

Has anyone got  the custom component "lightwave_smart.set_brightness" working?  When I run from developer tools/actions I just get the error "Failed to perform the action lightwave_smart.set_brightness. extra keys not allowed @ data['brightness']. Got None"

Regards,

Roger

**Comment by ikb42** [comment]
@RMMTSLLP @ins4neuk @roboberk 
please try this beta [v3.5.34-Beta](https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/releases/tag/v3.5.34-Beta)

**Comment by ins4neuk** [comment]
seems to be working spot on now. thank you so much for sorting it. i had got a work around but this is much better. cheers again for your support

**Comment by RMMTSLLP** [comment]
Yes I can confirm v3.5.34-Beta cures the set brightness issue many thanks
